### PR TITLE
WIP ipv6 support via ENV

### PR DESCRIPTION
**Pull request by Mossman1215**
added a flag for INET6 based on netstat's identifier for ipv6

### CODE REVIEW

**Comment by Mossman1215** [comment]
Seems to work on my local
tcantwell@DaMossman:~/Workspace/sensible-proxy$ curl -I -H "google.com" google.com --resolve google.com:80:[::1]
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Mon, 06 Jan 2020 23:42:08 GMT
Expires: Wed, 05 Feb 2020 23:42:08 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

tcantwell@DaMossman:~/Workspace/sensible-proxy$ curl -I -H "google.com" https://google.com --resolve google.com:443:[::1]
HTTP/2 301 
location: https://www.google.com/
content-type: text/html; charset=UTF-8
date: Mon, 06 Jan 2020 23:42:23 GMT
expires: Wed, 05 Feb 2020 23:42:23 GMT
cache-control: public, max-age=2592000
server: gws
content-length: 220
x-xss-protection: 0
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

**Comment by Mossman1215** [comment]
My intention would be to deploy via a separate server with just an ipv6 server

**Comment by indygriffiths** [comment]
Would it be better to support both IPv4 and IPv6 listeners at the same time for flexibility? Then I can do `LISTEN_INET=1 LISTEN_INET6=1 ./sensibleproxy` if I want both to run (so one server) or `LISTEN_INET6=1 ./sensibleproxy` if I only want an IPv6-only server.

**Comment by mateusz** [comment]
Can you try listening on `":"+proxy.port`? Looks like omitting the host part should end up listening on a dual stack socket, which is a default for Linux https://serverfault.com/questions/21657/semantics-of-and-0-0-0-0-in-dual-stack-oses. Your `[::]` might already be listening on both ipv4 and v6 anyway.

I guess you'd need to explain the usecase for listening on one but not the other. I don't see much harm in doing both at the same time by default. Are you worried about security groups not being configured?

**Comment by Mossman1215** [comment]
from my testing if you bind to 0.0.0.0 and have ipv6 capability golang will bind to both ipv4 and ipv6
so I expect the existing code will work if we add a ipv6 EIP to the existing box.
I think my changes are redundant.
I've been able to test on my local ubuntu which has both ipv4 and v6 and it appears to work.

**Pull request closed without merging**
